spring:
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onestoit?characterEncoding=utf-8&useSSL=false&useUnicode=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: com.onestoit.mapper.*
